set(RAPIDYENC_ROOT ${CMAKE_BINARY_DIR}/rapidyenc/src)
set(RAPIDYENC_LIBS
	${RAPIDYENC_ROOT}/rapidyenc-build/rapidyenc_static/librapidyenc.a
)

set(CMAKE_ARGS
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}
	-DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
	-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
	-DDISABLE_SHARED=ON
	-DDISABLE_TOOL=ON
	-DDISABLE_ENCODE=ON
	-DDISABLE_DECODE=OFF
	-DDISABLE_CRC=OFF
	-DDISABLE_AVX256=OFF
	-DDISABLE_CRCUTIL=OFF
	-DUSE_SANITIZERS=${USE_SANITIZERS}
)

if(DEFINED TOOLCHAIN_PREFIX)
	set(CMAKE_ARGS ${CMAKE_ARGS} -DTOOLCHAIN_PREFIX=${TOOLCHAIN_PREFIX})
endif()

if(CMAKE_SYSROOT)
	set(CMAKE_ARGS ${CMAKE_ARGS}
		-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
		-DCMAKE_SYSROOT=${CMAKE_SYSROOT}
		-DCMAKE_CXX_FLAGS=-I${CMAKE_SYSROOT}/usr/include/c++/v1
	)
endif()

ExternalProject_add(
	rapidyenc
	PREFIX			rapidyenc
	GIT_REPOSITORY	https://github.com/nzbgetcom/rapidyenc.git
	GIT_TAG			v1.1.1-20260821
	TLS_VERIFY		TRUE
	GIT_SHALLOW		TRUE
	GIT_PROGRESS	TRUE
	DOWNLOAD_EXTRACT_TIMESTAMP	TRUE
	BUILD_BYPRODUCTS ${RAPIDYENC_LIBS}
	CMAKE_ARGS		 ${CMAKE_ARGS}
	INSTALL_COMMAND	""
)

set(LIBS ${LIBS} ${RAPIDYENC_LIBS})
set(INCLUDES ${INCLUDES} ${RAPIDYENC_ROOT}/rapidyenc)
